# Generated by Django 4.2.8 on 2023-12-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager_user',
            name='password',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
