# Generated by Django 4.2.8 on 2023-12-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0004_rename_che_do_dieu_khien_van_kv_1_api_haodat_che_do_dieu_khien_van_kv_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_khecoc',
            old_name='che_do_dieu_khien_van_kv_2',
            new_name='che_do_dieu_khien_van_KV_2',
        ),
    ]
