# Generated by Django 4.2.8 on 2023-12-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0006_api_haodat_r_w_api_haodat_read_api_khecoc_r_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_haodat_r_w',
            name='che_do_hoat_dong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='che_do_hoat_dong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_thaiminh_r_w',
            name='che_do_hoat_dong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='change_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_bang_tay_dieu_khien_bom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_dieu_khien_van_KV_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_dieu_khien_van_KV_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_dieu_khien_van_KV_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_1_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_1_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_1_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_2_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_2_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_2_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_3_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_3_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_3_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_4_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_4_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_4_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_xac_nhan_lan_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_xac_nhan_lan_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_xac_nhan_lan_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_hang_ngay_xac_nhan_lan_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_xac_nhan_khu_vuc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_xac_nhan_lan_tuoi_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_xac_nhan_lan_tuoi_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_xac_nhan_lan_tuoi_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_r_w',
            name='che_do_xac_nhan_lan_tuoi_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_read',
            name='trang_thai_bom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_read',
            name='trang_thai_van_khu_vuc_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_read',
            name='trang_thai_van_khu_vuc_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_haodat_read',
            name='trang_thai_van_khu_vuc_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='change_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_bang_tay_dieu_khien_bom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_dieu_khien_van_KV_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_dieu_khien_van_KV_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_dieu_khien_van_KV_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_1_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_1_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_1_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_2_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_2_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_2_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_3_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_3_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_3_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_4_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_4_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_4_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_xac_nhan_lan_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_xac_nhan_lan_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_xac_nhan_lan_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_hang_ngay_xac_nhan_lan_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_xac_nhan_khu_vuc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_xac_nhan_lan_tuoi_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_xac_nhan_lan_tuoi_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_xac_nhan_lan_tuoi_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_r_w',
            name='che_do_xac_nhan_lan_tuoi_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_read',
            name='trang_thai_bom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_read',
            name='trang_thai_van_khu_vuc_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_read',
            name='trang_thai_van_khu_vuc_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_khecoc_read',
            name='trang_thai_van_khu_vuc_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='change_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_bang_tay_dieu_khien_bom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_dieu_khien_van_KV_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_dieu_khien_van_KV_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_dieu_khien_van_KV_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_1_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_1_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_1_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_2_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_2_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_2_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_3_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_3_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_3_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_4_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_4_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_dieu_khien_KV_4_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_xac_nhan_lan_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_xac_nhan_lan_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_xac_nhan_lan_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_hang_ngay_xac_nhan_lan_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_xac_nhan_khu_vuc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_xac_nhan_lan_tuoi_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_xac_nhan_lan_tuoi_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_xac_nhan_lan_tuoi_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_r_w',
            name='che_do_xac_nhan_lan_tuoi_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_read',
            name='trang_thai_bom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_read',
            name='trang_thai_van_khu_vuc_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_read',
            name='trang_thai_van_khu_vuc_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_thaiminh_read',
            name='trang_thai_van_khu_vuc_3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
