# Generated by Django 4.2.8 on 2023-12-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0007_api_haodat_r_w_che_do_hoat_dong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_haodat_read',
            name='che_do_online',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_read',
            name='che_do_online',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_thaiminh_read',
            name='che_do_online',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
