# Generated by Django 4.2.8 on 2024-01-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0008_api_haodat_read_che_do_online_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_bang_tay_dieu_khien_bom',
            new_name='Che_do_bang_tay_dieu_khien_bơm',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_dieu_khien_van_KV_1',
            new_name='Che_do_bang_tay_dieu_khien_van_KV1_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_dieu_khien_van_KV_2',
            new_name='Che_do_bang_tay_dieu_khien_van_KV1_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_dieu_khien_van_KV_3',
            new_name='Che_do_bang_tay_dieu_khien_van_KV1_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_dieu_khien_KV_1_1',
            new_name='Che_do_bang_tay_dieu_khien_van_KV1_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_dieu_khien_KV_1_2',
            new_name='Che_do_bang_tay_dieu_khien_van_KV2_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_dieu_khien_KV_1_3',
            new_name='Che_do_bang_tay_dieu_khien_van_KV2_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_dieu_khien_KV_2_1',
            new_name='Che_do_bang_tay_dieu_khien_van_KV2_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_dieu_khien_KV_2_2',
            new_name='Che_do_bang_tay_dieu_khien_van_KV2_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_dieu_khien_KV_2_3',
            new_name='Che_do_bang_tay_dieu_khien_van_KV3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_gio_bat_dau_tuoi_4',
            new_name='Che_do_tu_dong_gio_tuoi_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_phut_bat_dau_tuoi_1',
            new_name='Che_do_tu_dong_gio_tuoi_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_phut_bat_dau_tuoi_2',
            new_name='Che_do_tu_dong_gio_tuoi_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_phut_bat_dau_tuoi_3',
            new_name='Che_do_tu_dong_gio_tuoi_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_phut_bat_dau_tuoi_4',
            new_name='Che_do_tu_dong_phut_tuoi_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_thoi_gian_tuoi_1',
            new_name='Che_do_tu_dong_phut_tuoi_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_thoi_gian_tuoi_2',
            new_name='Che_do_tu_dong_phut_tuoi_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_thoi_gian_tuoi_3',
            new_name='Che_do_tu_dong_phut_tuoi_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_xac_nhan_lan_4',
            new_name='Che_do_tu_dong_xac_nhan_khu_vuc',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_dieu_khien_KV_3_1',
            new_name='Che_do_tu_dong_xac_nhan_lan_tuoi_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_dieu_khien_KV_3_2',
            new_name='Che_do_tu_dong_xac_nhan_lan_tuoi_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_dieu_khien_KV_3_3',
            new_name='Che_do_tu_dong_xac_nhan_lan_tuoi_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_dieu_khien_KV_4_1',
            new_name='Che_do_tu_dong_xac_nhan_lan_tuoi_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_dieu_khien_KV_4_2',
            new_name='Gio_bat_khu_vuc_1_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_dieu_khien_KV_4_3',
            new_name='Gio_bat_khu_vuc_1_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_gio_bat_dau_tuoi_1',
            new_name='Gio_bat_khu_vuc_1_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_gio_bat_dau_tuoi_2',
            new_name='Gio_bat_khu_vuc_1_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_gio_bat_dau_tuoi_3',
            new_name='Gio_bat_khu_vuc_2_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_gio_bat_dau_tuoi_1',
            new_name='Gio_bat_khu_vuc_2_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_gio_bat_dau_tuoi_2',
            new_name='Gio_bat_khu_vuc_2_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_gio_bat_dau_tuoi_3',
            new_name='Gio_bat_khu_vuc_2_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_gio_bat_dau_tuoi_4',
            new_name='Gio_bat_khu_vuc_3_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_phut_bat_dau_tuoi_1',
            new_name='Gio_bat_khu_vuc_3_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_phut_bat_dau_tuoi_2',
            new_name='Gio_bat_khu_vuc_3_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_phut_bat_dau_tuoi_3',
            new_name='Gio_bat_khu_vuc_3_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_phut_bat_dau_tuoi_4',
            new_name='Gio_bat_khu_vuc_4_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_thoi_gian_tuoi_4',
            new_name='Gio_bat_khu_vuc_4_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_xac_nhan_lan_1',
            new_name='Gio_bat_khu_vuc_4_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_xac_nhan_lan_2',
            new_name='Gio_bat_khu_vuc_4_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_hang_ngay_xac_nhan_lan_3',
            new_name='Gio_bat_khu_vuc_5_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_xac_nhan_khu_vuc',
            new_name='Gio_bat_khu_vuc_5_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_xac_nhan_lan_tuoi_1',
            new_name='Gio_bat_khu_vuc_5_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_xac_nhan_lan_tuoi_2',
            new_name='Gio_bat_khu_vuc_5_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_xac_nhan_lan_tuoi_3',
            new_name='Gio_bat_khu_vuc_6_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_xac_nhan_lan_tuoi_4',
            new_name='Gio_bat_khu_vuc_6_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='do_ph',
            new_name='Do_PH',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='trang_thai_bom',
            new_name='trang_thai_bom_1',
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_6_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_6_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_7_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_7_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_7_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_7_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_8_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_8_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_8_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_8_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_9_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_9_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_9_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_bat_khu_vuc_9_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_1_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_1_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_1_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_1_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_2_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_2_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_2_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_2_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_3_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_3_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_3_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_3_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_4_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_4_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_4_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_4_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_5_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_5_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_5_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_5_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_6_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_6_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_6_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_6_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_7_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_7_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_7_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_7_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_8_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_8_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_8_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_8_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_9_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_9_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_9_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Gio_tat_khu_vuc_9_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_1_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_1_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_1_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_1_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_2_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_2_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_2_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_2_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_3_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_3_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_3_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_3_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_4_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_4_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_4_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_4_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_5_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_5_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_5_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_5_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_6_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_6_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_6_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_6_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_7_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_7_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_7_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_7_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_8_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_8_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_8_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_8_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_9_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_9_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_9_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_bat_khu_vuc_9_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_1_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_1_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_1_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_1_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_2_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_2_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_2_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_2_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_3_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_3_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_3_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_3_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_4_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_4_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_4_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_4_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_5_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_5_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_5_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_5_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_6_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_6_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_6_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_6_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_7_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_7_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_7_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_7_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_8_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_8_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_8_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_8_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_9_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_9_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_9_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Phut_tat_khu_vuc_9_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_1_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_1_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_1_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_1_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_2_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_2_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_2_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_2_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_3_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_3_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_3_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_3_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_4_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_4_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_4_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_4_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_5_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_5_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_5_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_5_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_6_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_6_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_6_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_6_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_7_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_7_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_7_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_7_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_8_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_8_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_8_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_8_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_9_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_9_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_9_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w',
            name='Xac_nhan_khu_vuc_9_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_read',
            name='trang_thai_bom_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_read',
            name='trang_thai_van_khu_vuc_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_read',
            name='trang_thai_van_khu_vuc_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_read',
            name='trang_thai_van_khu_vuc_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_read',
            name='trang_thai_van_khu_vuc_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_read',
            name='trang_thai_van_khu_vuc_8',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
