# Generated by Django 4.2.8 on 2024-01-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0009_rename_che_do_bang_tay_dieu_khien_bom_api_khecoc_r_w_che_do_bang_tay_dieu_khien_bơm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_cai_dat_do_am',
            new_name='Che_do_tu_dong_cai_dat_do_am',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_do_am_max_1',
            new_name='Che_do_tu_dong_do_am_max_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_do_am_max_2',
            new_name='Che_do_tu_dong_do_am_max_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_do_am_max_3',
            new_name='Che_do_tu_dong_do_am_max_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_do_am_max_4',
            new_name='Che_do_tu_dong_do_am_max_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_do_am_min_1',
            new_name='Che_do_tu_dong_do_am_min_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_do_am_min_2',
            new_name='Che_do_tu_dong_do_am_min_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_do_am_min_3',
            new_name='Che_do_tu_dong_do_am_min_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_do_am_min_4',
            new_name='Che_do_tu_dong_do_am_min_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_thoi_gian_tuoi_1',
            new_name='Che_do_tu_dong_thoi_gian_tuoi_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_thoi_gian_tuoi_2',
            new_name='Che_do_tu_dong_thoi_gian_tuoi_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_thoi_gian_tuoi_3',
            new_name='Che_do_tu_dong_thoi_gian_tuoi_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_r_w',
            old_name='che_do_tu_dong_thoi_gian_tuoi_4',
            new_name='Che_do_tu_dong_thoi_gian_tuoi_4',
        ),
    ]
