# Generated by Django 4.2.8 on 2024-01-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0011_api_khecoc_r_w_bt_td_api_khecoc_r_w_hn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_khecoc_r_w_hn',
            name='update_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
