# Generated by Django 4.2.8 on 2024-01-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0013_api_khecoc_r_w_hn_1_api_khecoc_r_w_hn_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='do_am_dat',
            new_name='Do_am_dat',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='nhiet_do_dat',
            new_name='Nhiet_do_dat',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='trang_thai_bom_1',
            new_name='Trang_thai_bom_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='trang_thai_bom_2',
            new_name='Trang_thai_bom_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='trang_thai_van_khu_vuc_1',
            new_name='Trang_thai_van_khu_vuc_1',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='trang_thai_van_khu_vuc_2',
            new_name='Trang_thai_van_khu_vuc_2',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='trang_thai_van_khu_vuc_3',
            new_name='Trang_thai_van_khu_vuc_3',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='trang_thai_van_khu_vuc_4',
            new_name='Trang_thai_van_khu_vuc_4',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='trang_thai_van_khu_vuc_5',
            new_name='Trang_thai_van_khu_vuc_5',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='trang_thai_van_khu_vuc_6',
            new_name='Trang_thai_van_khu_vuc_6',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='trang_thai_van_khu_vuc_7',
            new_name='Trang_thai_van_khu_vuc_7',
        ),
        migrations.RenameField(
            model_name='api_khecoc_read',
            old_name='trang_thai_van_khu_vuc_8',
            new_name='Trang_thai_van_khu_vuc_8',
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w_hn_2',
            name='update_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
