# Generated by Django 4.2.8 on 2024-01-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0014_rename_do_am_dat_api_khecoc_read_do_am_dat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_khecoc_r_w_bt_td',
            old_name='che_do_hoat_dong',
            new_name='Che_do_hoat_dong',
        ),
    ]
