# Generated by Django 4.2.8 on 2024-01-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0015_rename_che_do_hoat_dong_api_khecoc_r_w_bt_td_che_do_hoat_dong'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_khecoc_r_w_bt_td',
            name='New_che_do',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w_hn_1',
            name='New_che_do',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_khecoc_r_w_hn_2',
            name='New_che_do',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
