from django.db import models

class Manager_User(models.Model):
    user = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    Household_Name = models.CharField(max_length=255)
    Area = models.CharField(max_length=255)
    Creat_day = models.DateField(auto_now_add=True)

# ===========================================================================================
class API_HaoDat_read(models.Model):
    update_time = models.TimeField(auto_now=True)
    nhiet_do_dat = models.FloatField(blank=True, null=True)
    do_am_dat = models.FloatField(blank=True, null=True)
    do_ph = models.FloatField(blank=True, null=True)
    trang_thai_van_khu_vuc_1 = models.IntegerField(blank=True, null=True)
    trang_thai_van_khu_vuc_2 = models.IntegerField(blank=True, null=True)
    trang_thai_van_khu_vuc_3 = models.IntegerField(blank=True, null=True)
    trang_thai_bom = models.IntegerField(blank=True, null=True)

class API_HaoDat_R_W(models.Model):
    change_status = models.IntegerField(blank=True, null=True)
    update_time = models.TimeField(auto_now=True)
    che_do_dieu_khien_van_KV_1 = models.IntegerField(blank=True, null=True)
    che_do_dieu_khien_van_KV_2 = models.IntegerField(blank=True, null=True)
    che_do_dieu_khien_van_KV_3 = models.IntegerField(blank=True, null=True)
    che_do_bang_tay_dieu_khien_bom = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_1_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_1_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_1_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_2_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_2_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_2_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_3_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_3_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_3_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_4_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_4_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_4_3 = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_khu_vuc = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_lan_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_lan_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_lan_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_lan_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_gio_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_gio_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_gio_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_gio_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_phut_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_phut_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_phut_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_phut_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_min_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_min_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_min_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_min_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_max_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_max_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_max_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_max_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_thoi_gian_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_thoi_gian_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_thoi_gian_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_thoi_gian_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_cai_dat_do_am = models.IntegerField(blank=True, null=True)
    che_do_hoat_dong = models.IntegerField(blank=True, null=True)

# ===========================================================================================
class API_KheCoc_read(models.Model):
    update_time = models.TimeField(auto_now=True)
    nhiet_do_dat = models.FloatField(blank=True, null=True)
    do_am_dat = models.FloatField(blank=True, null=True)
    do_ph = models.FloatField(blank=True, null=True)
    trang_thai_van_khu_vuc_1 = models.IntegerField(blank=True, null=True)
    trang_thai_van_khu_vuc_2 = models.IntegerField(blank=True, null=True)
    trang_thai_van_khu_vuc_3 = models.IntegerField(blank=True, null=True)
    trang_thai_bom = models.IntegerField(blank=True, null=True)

class API_KheCoc_R_W(models.Model):
    change_status = models.IntegerField(blank=True, null=True)
    update_time = models.TimeField(auto_now=True)
    che_do_dieu_khien_van_KV_1 = models.IntegerField(blank=True, null=True)
    che_do_dieu_khien_van_KV_2 = models.IntegerField(blank=True, null=True)
    che_do_dieu_khien_van_KV_3 = models.IntegerField(blank=True, null=True)
    che_do_bang_tay_dieu_khien_bom = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_1_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_1_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_1_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_2_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_2_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_2_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_3_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_3_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_3_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_4_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_4_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_4_3 = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_khu_vuc = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_lan_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_lan_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_lan_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_lan_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_gio_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_gio_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_gio_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_gio_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_phut_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_phut_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_phut_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_phut_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_min_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_min_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_min_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_min_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_max_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_max_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_max_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_max_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_thoi_gian_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_thoi_gian_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_thoi_gian_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_thoi_gian_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_cai_dat_do_am = models.IntegerField(blank=True, null=True)
    che_do_hoat_dong = models.IntegerField(blank=True, null=True)

# ===========================================================================================
class API_ThaiMinh_read(models.Model):
    update_time = models.TimeField(auto_now=True)
    nhiet_do_dat = models.FloatField(blank=True, null=True)
    do_am_dat = models.FloatField(blank=True, null=True)
    do_ph = models.FloatField(blank=True, null=True)
    trang_thai_van_khu_vuc_1 = models.IntegerField(blank=True, null=True)
    trang_thai_van_khu_vuc_2 = models.IntegerField(blank=True, null=True)
    trang_thai_van_khu_vuc_3 = models.IntegerField(blank=True, null=True)
    trang_thai_bom = models.IntegerField(blank=True, null=True)

class API_ThaiMinh_R_W(models.Model):
    change_status = models.IntegerField(blank=True, null=True)
    update_time = models.TimeField(auto_now=True)
    che_do_dieu_khien_van_KV_1 = models.IntegerField(blank=True, null=True)
    che_do_dieu_khien_van_KV_2 = models.IntegerField(blank=True, null=True)
    che_do_dieu_khien_van_KV_3 = models.IntegerField(blank=True, null=True)
    che_do_bang_tay_dieu_khien_bom = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_1_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_1_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_1_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_2_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_2_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_2_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_3_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_3_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_3_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_4_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_4_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_dieu_khien_KV_4_3 = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_khu_vuc = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_lan_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_lan_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_lan_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_xac_nhan_lan_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_gio_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_gio_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_gio_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_gio_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_phut_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_phut_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_phut_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_phut_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_min_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_min_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_min_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_min_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_max_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_max_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_max_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_do_am_max_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_thoi_gian_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_thoi_gian_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_thoi_gian_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_thoi_gian_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_tu_dong_cai_dat_do_am = models.IntegerField(blank=True, null=True)
    che_do_hoat_dong = models.IntegerField(blank=True, null=True)
