from django.db import models

class Manager_User(models.Model):
    user = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    Household_Name = models.CharField(max_length=255)
    Area = models.CharField(max_length=255)
    Creat_day = models.DateField(auto_now_add=True)

class API_HaoDat(models.Model):
    nhiet_do_dat = models.FloatField(blank=True, null=True)
    do_am_dat = models.FloatField(blank=True, null=True)
    do_ph = models.FloatField(blank=True, null=True)
    che_do_dieu_khien_van_kv_1 = models.BooleanField(default=False)
    che_do_dieu_khien_van_kv_2 = models.BooleanField(default=False)
    che_do_dieu_khien_van_kv_3 = models.BooleanField(default=False)
    che_do_bang_tay_dieu_khien_bom = models.BooleanField(default=False)
    che_do_hang_ngay_thoi_gian_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_5 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_6 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_5 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_6 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_5 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_6 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_1 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_2 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_3 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_4 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_5 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_6 = models.BooleanField(default=False)
    che_do_hang_ngay_dieu_khien_kv_1 = models.BooleanField(default=False)
    che_do_hang_ngay_dieu_khien_kv_2 = models.BooleanField(default=False)
    che_do_hang_ngay_dieu_khien_kv_3 = models.BooleanField(default=False)

class API_KheCoc(models.Model):
    nhiet_do_dat = models.FloatField(blank=True, null=True)
    do_am_dat = models.FloatField(blank=True, null=True)
    do_ph = models.FloatField(blank=True, null=True)
    che_do_dieu_khien_van_kv_1 = models.BooleanField(default=False)
    che_do_dieu_khien_van_kv_2 = models.BooleanField(default=False)
    che_do_dieu_khien_van_kv_3 = models.BooleanField(default=False)
    che_do_bang_tay_dieu_khien_bom = models.BooleanField(default=False)
    che_do_hang_ngay_thoi_gian_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_5 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_6 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_5 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_6 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_5 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_6 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_1 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_2 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_3 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_4 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_5 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_6 = models.BooleanField(default=False)
    che_do_hang_ngay_dieu_khien_kv_1 = models.BooleanField(default=False)
    che_do_hang_ngay_dieu_khien_kv_2 = models.BooleanField(default=False)
    che_do_hang_ngay_dieu_khien_kv_3 = models.BooleanField(default=False)

class API_ThaiMinh(models.Model):
    nhiet_do_dat = models.FloatField(blank=True, null=True)
    do_am_dat = models.FloatField(blank=True, null=True)
    do_ph = models.FloatField(blank=True, null=True)
    che_do_dieu_khien_van_kv_1 = models.BooleanField(default=False)
    che_do_dieu_khien_van_kv_2 = models.BooleanField(default=False)
    che_do_dieu_khien_van_kv_3 = models.BooleanField(default=False)
    che_do_bang_tay_dieu_khien_bom = models.BooleanField(default=False)
    che_do_hang_ngay_thoi_gian_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_5 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_thoi_gian_tuoi_6 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_5 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_gio_bat_dau_tuoi_6 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_1 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_2 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_3 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_4 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_5 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_phut_bat_dau_tuoi_6 = models.IntegerField(blank=True, null=True)
    che_do_hang_ngay_xac_nhan_lan_1 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_2 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_3 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_4 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_5 = models.BooleanField(default=False)
    che_do_hang_ngay_xac_nhan_lan_6 = models.BooleanField(default=False)
    che_do_hang_ngay_dieu_khien_kv_1 = models.BooleanField(default=False)
    che_do_hang_ngay_dieu_khien_kv_2 = models.BooleanField(default=False)
    che_do_hang_ngay_dieu_khien_kv_3 = models.BooleanField(default=False)